Hw02 unpack string
korici/otus_go pull request #2
Opened 2022-12-11 17:12 UTC by korici

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-13 19:31 UTC, Nikscorp requested changes
Екатерина, добрый вечер!

Спасибо за проделанную работу, код корректно работает на достаточно большом количестве входных данных.
Посмотрел задание, оставил замечания в PR.

В данный момент не могу принять работу, буду ждать исправлений.

> **P.S.**
> 
> Нотация:
> 
> - CRIT: критическое замечание ведущее к значительному снижению баллов
> - WARN: некритическое замечание ведущее к незначительному снижению баллов (часто по критерию чистого кода / аккуратности)
> - NB: nota bene — что-то на что нужно обратить внимание (например в реальных проектах), совет, к снижению баллов не ведет
> - GREAT: часть проекта, которую хочется похвалить, выделить
> 
> Проверяющие тоже люди — в своих замечаниях я могу что-то упустить или ошибиться, в случае если вы не согласны с замечаниями — не стесняйтесь их оспаривать.
> 
> Если что-то нужно перепроверить, заапрувить, принять инвайт, поднять оценку, то прошу следовать данной последовательности:
> 
> 1. Написать в чате со мной с ДЗ на сайте ОТУС-а и перекинуть ДЗ на меня со статусом "Нужно проверить"
> 2. Написать на GitHub-е
> 3. Продублировать мне сообщение в корпоративном Slack-е: (Nikita Voynov)

2022-12-13 19:31 UTC, Nikscorp commented on .golangci.yml
> +  go: '1.17'
WARN: зачем? Используйте обновленный шаблон из репозитория, там go 1.19 и обновленный список линтеров

2022-12-13 19:31 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +			b.Reset()
NB: лучше сразу `return`, reset тут не нужен, память за ваш почистит GC

2022-12-13 19:31 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +		case isEkr == 0 && r <= '9':
WARN: забыли сравнить r с '0', в ascii есть символы с кодами меньше чем у '0', например пробел.
Также на это нужен тест

2022-12-13 19:31 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +				for i := 0; i < int(r-'0'); i++ {
NB: для этого есть strings.Repeat

2022-12-13 19:31 UTC, Nikscorp commented on hw02_unpack_string/unpack_test.go
> +		{input: `qwe\4\5`, expected: `qwe45`},
WARN: нет тестов на юникодные символы более 1 байта, кириллица, иероглифы, emoji и вот это вот все

2022-12-13 19:31 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +		err = nil
NB: она и так nil

2022-12-13 19:31 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +		case isEkr == 0 && r <= '9':
вернее не забыли — а проверили в другом месте и вернули ошибку, хотя тут не должно быть ошибки

2022-12-13 19:31 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +	case chksd <= 'Z':
WARN: тут и ниже тоже много символов потеряли, например "*" будет распознана как невалидная строка, хотя она вполне себе валидная

2022-12-13 19:31 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +	case chksd <= 'z':
NB: тут if внутри свитча выглядит странно можно все это оставить в switch под &&

2022-12-14 15:15 UTC, korici commented on .golangci.yml
> +  go: '1.17'
В репозитории есть линтеры, которые уже не поддерживаются и на это появляются warning. Рекоментуют 2 вариант - убрать эти литеры или поставить версию 1.17. Видимо я выбрала не тот вариант. Уберу литреры у себя (rowserrcheck, sqlclosecheck и wastedassign)
https://github.com/golangci/golangci-lint/issues/2649

2022-12-14 15:25 UTC, korici commented on hw02_unpack_string/unpack.go
> +		case isEkr == 0 && r <= '9':
Как именно должна вести себя программа в отношении символов пустой строки и др. символов? Я поняла так, что разрешены только латиница, цифры и \, остальное должно попадать в ошибку, из примеров видно что есть только эти символы => остальное ошибка (видимо сделала неправильный вывод)

2022-12-14 15:32 UTC, Nikscorp commented on .golangci.yml
> +  go: '1.17'
Лучше синхронизировать их из шаблона проекта. Недавно его обновляли. Если после этого что-то дает false positive срабатывание / список литеров не актуален — нужно написать преподавателям.

2022-12-14 15:36 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +		case isEkr == 0 && r <= '9':
Все остальные символы лучше просто переносить как есть c учетом правил распаковки.

В задании
> ... распаковку строки, содержащую повторяющиеся символы/руны, например
Повторяющиеся руны подразумевают любые символы, но согласен, формулировка туманная.

2022-12-14 15:52 UTC, korici commented on hw02_unpack_string/unpack.go
> +	case chksd <= 'z':
переносить нельзя - если придёт цифра , то сейчас она зайдёт в case chksd <= '9', в if не попадет и return ErrInvalidString не будет
...
	case chksd <= '9':
		if chksd < '0' {
			return ErrInvalidString
		}
...
Если сделать как ниже, то цифра в свой case не зайдет и попадет в "chksd <= 'Z' && chksd < 'A'", а оттуда в ошибку, хотя цифра не должна
...
	case chksd <= '9' && chksd < '0' :
			return ErrInvalidString
	case chksd <= 'Z' && chksd < 'A':
			return ErrInvalidString
...

2022-12-15 02:33 UTC, Nikscorp approved these changes
Екатерина, добрый день!

Код стал лучше, отлично.
Оставил еще несколько замечаний в комментариях к PR.
Текущая оценка 8 баллов из 10.

2022-12-15 02:33 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +		case isEkr == 0 && unicode.IsDigit(r):
WARN: Использование `unicode.IsDigit`. Несмотря на то, что в задании указана рекомендация по использованию данной функции я советовал бы отнестись к ней с осторожностью. Помимо арабских цифр `0, 1 ... 9` она трактует как цифры также иные символы, например отсюда https://www.fileformat.info/info/unicode/category/Nd/list.htm . Если вы трактуете задание таким образом, то необходимо покрыть данный функционал юнит-тестами, также прошу учесть, что с такой трактовкой ваш код также не будет работать, так как digit-символы вне `0...9` не смогут привестись к int с помощью `strconv.Atoi`, пример: https://go.dev/play/p/zPCRUQsqPuG. Я обсужу с руководителем курса рекомендацию по использованию `unicode.IsDigit`. Я рекомендую проверять символы простым сравнением с байтами `0` и `9`, а к инту приводить простым вычитанием из символа `'0'` с расширением типа.

2022-12-15 02:33 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +	isEkr := 0
WARN: ну это явно должно быть типом `bool`

2022-12-15 02:33 UTC, Nikscorp commented on hw02_unpack_string/unpack_test.go
> +		{input: `sd sУра`, expected: `sd sУра`},
WARN: я не увидел тестов на юникодные символы более 1 байта, кириллица, иероглифы, emoji и вот это вот все

2022-12-15 02:34 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +		case isEkr == 0 && unicode.IsDigit(r):
PS на это тоже лучше добавить тесты

2022-12-17 18:28 UTC, merged

2022-12-18 17:16 UTC, Nikscorp reviewed
Все отлично, замечания исправлены, повышаю балл до максимального!